% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Jan-2015 9:11:03
%  MATLAB version: 8.4.0.150421 (R2014b)
% -------------------------------------------------------------------
clear
close all
clc
IMage = imread('//5.tif');
imtool(IMage);
%使用MATLAB自带函数实现均值滤波
key = fspecial('average',3);%均值滤波算子
Pave = imfilter(IMage,key,'symmetric');
imtool(Pave);

