% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Jan-2015 9:11:03
%  MATLAB version: 8.4.0.150421 (R2014b)
% -------------------------------------------------------------------
clear
close all
clc
mex ImageAve.cpp;
arr=[11:19;21:29;31:39;41:49;51:59;61:69];
IMage = imread('//5.tif');
rows=[1 3];
cols=[2:4 5 9];
[rarr,rdims]=ImageAve(arr,rows,cols);
